server:
  port: 8038
spring:
  application:
    name: swag-home
  data:
    mongodb:
      uri: mongodb+srv://JuancaJcA:5iNlK1vFPU6KWwpq@labooncluster.ptkenzc.mongodb.net/?retryWrites=true&w=majority
      database: Software

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
#      defaultZone: http://swag-discovery:8703/eureka/
      defaultZone: http://localhost:8703/eureka/